public class Test {
    public static void main (String[] args) {
        
        Quadrilateral shape1 = new Quadrilateral(); 
        Object shape2 = new Kite(); 
        Quadrilateral shape3 = new Trapezium(); 
        Object shape4 = new Parallelogram();
        Parallelogram shape5 = new Rhombus(); 
        Quadrilateral shape6 = new Rectangle();
        Parallelogram shape7 = new Square(); 
        Rectangle shape8 = new Square();
        
//        System.out.println(shape1.name);
//        System.out.println(shape2.name);
//        System.out.println(shape3.name);
//        System.out.println(shape4.name);
//        System.out.println(shape5.name);
//        System.out.println(shape6.name);
//        System.out.println(shape7.name);
//        shape1.method1();
//        shape1.method2();
//        shape1.method3();
//        shape1.method4();
//        shape2.method1();
//        shape2.method2();
//        shape2.method3();
//        shape2.method4();
//        shape3.method1();
//        shape3.method2();
//        shape3.method3();
//        shape3.method4();
//        shape4.method1();
//        shape4.method2();
//        shape4.method3();
//        shape4.method4();
//        shape5.method1();
//        shape5.method2();
//        shape5.method3();
//        shape5.method4();
//        shape6.method1();
//        shape6.method2();
//        shape6.method3();
//        shape6.method4();
//        shape7.method1();
//        shape7.method2();
//        shape7.method3();
//        shape7.method4();
//        System.out.println(shape8.compareTo(shape8));
//        ((Quadrilateral) shape1).method1();
//        ((Quadrilateral) shape2).method1();
//        ((Quadrilateral) shape3).method1();
//        ((Quadrilateral) shape4).method1();
//        ((Quadrilateral) shape5).method1();
//        ((Quadrilateral) shape6).method1();
//        ((Quadrilateral) shape7).method1();
//        ((Quadrilateral) shape1).method2();
//        ((Quadrilateral) shape2).method2();
//        ((Quadrilateral) shape3).method2();
//        ((Quadrilateral) shape4).method2();
//        ((Quadrilateral) shape5).method2();
//        ((Quadrilateral) shape6).method2();
//        ((Quadrilateral) shape7).method2();
//        ((Quadrilateral) shape1).method3();
//        ((Quadrilateral) shape2).method3();
//        ((Quadrilateral) shape3).method3();
//        ((Quadrilateral) shape4).method3();
//        ((Quadrilateral) shape5).method3();
//        ((Quadrilateral) shape6).method3();
//        ((Quadrilateral) shape7).method3();
//        ((Object) shape1).method1();
//        ((Object) shape2).method1();
//        ((Object) shape3).method1();
//        ((Object) shape4).method1();
//        ((Object) shape5).method1();
//        ((Object) shape6).method1();
//        ((Object) shape7).method1();
//        ((Object) shape1).method2();
//        ((Object) shape2).method2();
//        ((Object) shape3).method2();
//        ((Object) shape4).method2();
//        ((Object) shape5).method2();
//        ((Object) shape6).method2();
//        ((Object) shape7).method2();
//        ((Object) shape1).method3();
//        ((Object) shape2).method3();
//        ((Object) shape3).method3();
//        ((Object) shape4).method3();
//        ((Object) shape5).method3();
//        ((Object) shape6).method3();
//        ((Object) shape7).method3();
//        ((Kite) shape1).method1();
//        ((Kite) shape2).method1();
//        ((Kite) shape3).method1();
//        ((Kite) shape4).method1();
//        ((Kite) shape5).method1();
//        ((Kite) shape6).method1();
//        ((Kite) shape7).method1();
//        ((Kite) shape1).method2();
//        ((Kite) shape2).method2();
//        ((Kite) shape3).method2();
//        ((Kite) shape4).method2();
//        ((Kite) shape5).method2();
//        ((Kite) shape6).method2();
//        ((Kite) shape7).method2();
//        ((Kite) shape1).method3();
//        ((Kite) shape2).method3();
//        ((Kite) shape3).method3();
//        ((Kite) shape4).method3();
//        ((Kite) shape5).method3();
//        ((Kite) shape6).method3();
//        ((Kite) shape7).method3();
//        ((Parallelogram) shape1).method1();
//        ((Parallelogram) shape2).method1();
//        ((Parallelogram) shape3).method1();
//        ((Parallelogram) shape4).method1();
//        ((Parallelogram) shape5).method1();
//        ((Parallelogram) shape6).method1();
//        ((Parallelogram) shape7).method1();
//        ((Parallelogram) shape1).method2();
//        ((Parallelogram) shape2).method2();
//        ((Parallelogram) shape3).method2();
//        ((Parallelogram) shape4).method2();
//        ((Parallelogram) shape5).method2();
//        ((Parallelogram) shape6).method2();
//        ((Parallelogram) shape7).method2();
//        ((Parallelogram) shape1).method3();
//        ((Parallelogram) shape2).method3();
//        ((Parallelogram) shape3).method3();
//        ((Parallelogram) shape4).method3();
//        ((Parallelogram) shape5).method3();
//        ((Parallelogram) shape6).method3();
//        ((Parallelogram) shape7).method3();
//        ((Trapezium) shape1).method1();
//        ((Trapezium) shape2).method1();
//        ((Trapezium) shape3).method1();
//        ((Trapezium) shape4).method1();
//        ((Trapezium) shape5).method1();
//        ((Trapezium) shape6).method1();
//        ((Trapezium) shape7).method1();
//        ((Trapezium) shape1).method2();
//        ((Trapezium) shape2).method2();
//        ((Trapezium) shape3).method2();
//        ((Trapezium) shape4).method2();
//        ((Trapezium) shape5).method2();
//        ((Trapezium) shape6).method2();
//        ((Trapezium) shape7).method2();
//        ((Trapezium) shape1).method3();
//        ((Trapezium) shape2).method3();
//        ((Trapezium) shape3).method3();
//        ((Trapezium) shape4).method3();
//        ((Trapezium) shape5).method3();
//        ((Trapezium) shape6).method3();
//        ((Trapezium) shape7).method3();
//        ((Rhombus) shape1).method1();
//        ((Rhombus) shape2).method1();
//        ((Rhombus) shape3).method1();
//        ((Rhombus) shape4).method1();
//        ((Rhombus) shape5).method1();
//        ((Rhombus) shape6).method1();
//        ((Rhombus) shape7).method1();
//        ((Rhombus) shape1).method2();
//        ((Rhombus) shape2).method2();
//        ((Rhombus) shape3).method2();
//        ((Rhombus) shape4).method2();
//        ((Rhombus) shape5).method2();
//        ((Rhombus) shape6).method2();
//        ((Rhombus) shape7).method2();
//        ((Rhombus) shape1).method3();
//        ((Rhombus) shape2).method3();
//        ((Rhombus) shape3).method3();
//        ((Rhombus) shape4).method3();
//        ((Rhombus) shape5).method3();
//        ((Rhombus) shape6).method3();
//        ((Rhombus) shape7).method3();
//        ((Rectangle) shape1).method1();
//        ((Rectangle) shape2).method1();
//        ((Rectangle) shape3).method1();
//        ((Rectangle) shape4).method1();
//        ((Rectangle) shape5).method1();
//        ((Rectangle) shape6).method1();
//        ((Rectangle) shape7).method1();
//        ((Rectangle) shape1).method2();
//        ((Rectangle) shape2).method2();
//        ((Rectangle) shape3).method2();
//        ((Rectangle) shape4).method2();
//        ((Rectangle) shape5).method2();
//        ((Rectangle) shape6).method2();
//        ((Rectangle) shape7).method2();
//        ((Rectangle) shape1).method3();
//        ((Rectangle) shape2).method3();
//        ((Rectangle) shape3).method3();
//        ((Rectangle) shape4).method3();
//        ((Rectangle) shape5).method3();
//        ((Rectangle) shape6).method3();
//        ((Rectangle) shape7).method3();
//        ((Square) shape1).method1();
//        ((Square) shape2).method1();
//        ((Square) shape3).method1();
//        ((Square) shape4).method1();
//        ((Square) shape5).method1();
//        ((Square) shape6).method1();
//        ((Square) shape7).method1();
//        ((Square) shape1).method2();
//        ((Square) shape2).method2();
//        ((Square) shape3).method2();
//        ((Square) shape4).method2();
//        ((Square) shape5).method2();
//        ((Square) shape6).method2();
//        ((Square) shape7).method2();
//        ((Square) shape1).method3();
//        ((Square) shape2).method3();
//        ((Square) shape3).method3();
//        ((Square) shape4).method3();
//        ((Square) shape5).method3();
//        ((Square) shape6).method3();
//        ((Square) shape7).method3();
        
    }
}